name: Build xDripSwift

on:
  push:
    branches:
      - master # O la rama principal que uses, ej: main

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Archive the application
        run: |
          xcodebuild archive \
            -project xDrip.xcodeproj \
            -scheme xDrip \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/xDrip.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: Export the .ipa
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/xDrip.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload Artifact (Compiled App)
        uses: actions/upload-artifact@v4
        with:
          name: xDrip-App
          path: build/xDrip.ipa
